[package]
name = "modde-xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "modde-rs tooling CLI (cargo xtask)"
publish = false

[[bin]]
name = "modde-xtask"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
semver.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
harbor-xtask = { git = "https://github.com/caniko/harbor-rs.git", rev = "c4ffa5d9b9232eae1f6693dfbcbcdd2548f31592" }

[lints]
workspace = true
