[package]
name = "modde-games"
version.workspace = true
description = "Game plugin implementations for modde"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../../README.md"
documentation = "https://docs.rs/modde-games"
include = [
  "../../LICENSE",
  "../../README.md",
  "CHANGELOG.md",
  "Cargo.toml",
  "src/**",
  "tests/**",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[features]
default = ["all-games", "postgres", "linux-integrations", "macos-integrations"]
all-games = [
  "bethesda",
  "gamebryo",
  "cyberpunk",
  "ue4",
  "bg3",
  "stardew",
  "bannerlord",
  "witcher3",
  "oblivion-remastered",
]
bethesda = ["modde-core/bethesda-archives", "dep:lz4_flex", "dep:serde_yaml_ng"]
gamebryo = ["modde-core/bethesda-archives"]
cyberpunk = ["dep:which"]
ue4 = []
bg3 = []
stardew = []
bannerlord = []
witcher3 = []
oblivion-remastered = ["modde-core/bethesda-archives"]
postgres = ["modde-core/postgres"]
linux-integrations = ["dep:which"]
macos-integrations = ["dep:which"]
windows-integrations = ["modde-core/windows-integrations", "dep:which"]

[dependencies]
modde-core = { workspace = true }
fomod-oxide = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true, optional = true }
toml = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true, features = ["query"] }
zip = { workspace = true }
futures = { workspace = true }
flate2 = { workspace = true }
lz4_flex = { workspace = true, optional = true }
tracing = { workspace = true }
smallvec = { workspace = true }
dashmap = { workspace = true }
which = { workspace = true, optional = true }
open = { workspace = true }
xxhash-rust = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
tracing-test = { version = "0.2.6", features = ["no-env-filter"] }
